# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proiecte', '0003_auto_20151130_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposition',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiecte.ProjectRole'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structuri.Membru'),
        ),
    ]
