# Generated by Django 4.1.7 on 2023-06-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0008_echipa'),
        ('album', '0008_auto_20211031_2218'),
        ('proiecte', '0004_auto_20211031_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_form', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='taskitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proiecte.taskstate'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Joasă'), (2, 'Normală'), (3, 'Înaltă')], default=2),
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='structuri.membru'),
        ),
        migrations.CreateModel(
            name='ProjectBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublines', to='proiecte.projectbudgetline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiecte.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBudgetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sum', models.FloatField()),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='proiecte.projectbudgetline')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eveniment')),
                ('task_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proiecte.taskitem')),
            ],
        ),
    ]
