# Generated by Django 4.1.7 on 2023-07-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proiecte', '0006_projectbudgetentry_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proiecte.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectobjective',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='proiecte.project'),
            preserve_default=False,
        ),
    ]
