# Generated by Django 4.1.7 on 2023-02-24 21:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('pages', '0003_wikipage_wikipagerelatedlink_delete_freeformpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify pages by this category', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Wiki Category',
                'verbose_name_plural': 'Wiki Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='pages.wikipage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='pages.wikipagecategory'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.WikiPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
