# Generated by Django 4.1.7 on 2024-09-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_id', models.PositiveIntegerField()),
                ('requires_reply', models.BooleanField(default=False)),
                ('reply_options', models.JSONField()),
                ('actor_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to='contenttypes.contenttype')),
                ('target_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email-list', 'Email List'), ('slack', 'Slack'), ('sms', 'SMS')], default='email-list', max_length=255)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificatonMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='notifications.notification')),
            ],
        ),
    ]
