language: python
python:
  - "2.7"
# command to install dependencies
services:
- mysql
- redis-server

env:
- DJANGO=1.8.7 DB=mysql

before_install:
- export DJANGO_SETTINGS_MODULE=scoutfile3.settings
- export BOTO_CONFIG=/tmp/nowhere

install:
  - pip install -r deploy/requirements.txt
# command to run tests

before_script:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
 - cp web/scoutfile3/local_settings.travis.py web/scoutfile3/local_settings.py
 - mkdir logs

script:
  - cd web && python manage.py test

notifications:
  email:
    recipients:
      - andrei.avram@albascout.ro
    on_success: never
    on_failure: always

deploy:

  - provider: script
    script: cd web && fab -H yeti.albascout.ro:24 -u scoutfile --password $DEPLOY_PASSWORD
    on:
      branch: master
    skip_cleanup: true

  - provider: script
    script: cd web && fab -H yeti.albascout.ro:24 -u scoutfile --password $DEPLOY_PASSWORD
    on:
      branch: develop
    skip_cleanup: true

