version: '2'
services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/current_dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD="root123."
      - MYSQL_DATABASE=scoutfile_local

  redis:
    image: redis:3.2-alpine
    ports:
      - "63791:6379"
    volumes:
      - ./data/redis:/data

  memcached:
    image: memcached:1.4
    ports:
     - "11211:11211"

  web:
    build: .
    links:
      - redis
      - postgres
      - memcached
      - mysql

    working_dir: /scoutfile/web/
    command: ["/wait-for-it.sh", "mysql:3306", "--", "python", "/scoutfile/web/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/scoutfile



    ports:
     - "8000:8000"