# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documente', '0004_auto_20150330_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asocieredocument',
            name='document_ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asociere', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='asocieredocument',
            name='tip_asociere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documente.TipAsociereDocument'),
        ),
        migrations.AlterField(
            model_name='chitanta',
            name='casier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.Membru'),
        ),
        migrations.AlterField(
            model_name='deciziecotizatie',
            name='categorie',
            field=models.CharField(choices=[('local', 'Local'), ('national', 'Național'), ('local-social', 'Local (social)'), ('national-social', 'Național (social)')], default='normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='decizierezervarenumere',
            name='tip_rezervare',
            field=models.CharField(choices=[('chitantier', 'Chitanțier'), ('facturier', 'Facturier'), ('io', 'Registru intrări / ieșiri'), ('intern', 'Registru intern')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='tip_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documente.TipDocument'),
        ),
        migrations.AlterField(
            model_name='platacotizatietrimestru',
            name='chitanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documente.ChitantaCotizatie'),
        ),
        migrations.AlterField(
            model_name='platacotizatietrimestru',
            name='tip_inregistrare',
            field=models.CharField(choices=[('normal', 'Plată normală'), ('inactiv', 'Inactiv')], default='normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='registru',
            name='mod_functionare',
            field=models.CharField(choices=[('auto', 'Automat'), ('manual', 'Manual')], default='auto', help_text='Registrul cu numerotare automată își gestionează singur numerele de înregistrare', max_length=255, verbose_name='Tip numerotare'),
        ),
        migrations.AlterField(
            model_name='registru',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structuri.Membru'),
        ),
        migrations.AlterField(
            model_name='registru',
            name='tip_registru',
            field=models.CharField(choices=[('chitantier', 'Chitanțier'), ('facturier', 'Facturier'), ('io', 'Registru intrări / ieșiri'), ('intern', 'Registru intern')], max_length=255),
        ),
    ]
