# Generated by Django 4.1.7 on 2023-06-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0006_alter_bankstatementitem_unique_together'),
        ('documente', '0006_alter_document_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='platacotizatietrimestru',
            name='payment_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financiar.paymentdocument'),
        ),
    ]
