# Generated by Django 4.1.7 on 2023-07-15 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0009_paymentdomain_paymentdocument_domain'),
        ('documente', '0007_platacotizatietrimestru_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitanta',
            name='payment_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financiar.paymentdocument'),
        ),
    ]
