# Generated by Django 4.1.7 on 2023-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documente', '0008_chitanta_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitantacotizatie',
            name='tip',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Virament bancar (OP)'), (3, 'Depunere numerar')], default=1, verbose_name='Tip plată'),
        ),
    ]
