# Generated by Django 4.1.7 on 2023-06-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Pat'), (2, 'Pat supraetajat, jos'), (3, 'Pat supraetajat, sus'), (4, 'Loc de cort, 1 / 2 persoane'), (5, 'Loc de cort, 3 / 5 persoane'), (6, 'Mâncare gătită / catering'), (7, 'Loc de gătit în bucătărie')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.space')),
            ],
        ),
    ]
