# Generated by Django 4.1.7 on 2023-06-02 09:26

from django.db import migrations, models
import django.utils.timezone
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='file',
            new_name='statement_file',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='month',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('ron', 'RON'), ('eur', 'EUR'), ('usd', 'USD')], default='ron', max_length=3),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementitem',
            name='account_number',
            field=localflavor.generic.models.IBANField(default='', include_countries=None, max_length=34, use_nordea_extensions=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankstatementitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementitem',
            unique_together={('account_number', 'reference')},
        ),
    ]
