# Generated by Django 4.1.7 on 2023-06-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0003_rename_file_bankstatement_statement_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatementitem',
            options={'ordering': ['order', 'account_number']},
        ),
        migrations.AddField(
            model_name='bankstatementitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankstatementitem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financiar.bankstatement'),
        ),
    ]
