# Generated by Django 4.1.7 on 2023-06-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0004_alter_bankstatementitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatementitem',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementitem',
            unique_together={('account_number', 'reference', 'transaction_date')},
        ),
    ]
