# Generated by Django 4.1.7 on 2023-06-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0005_alter_bankstatementitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankstatementitem',
            unique_together={('account_number', 'reference', 'transaction_date', 'value', 'description')},
        ),
    ]
