# Generated by Django 4.1.7 on 2023-06-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0010_utilizator_slack_email'),
        ('documente', '0007_platacotizatietrimestru_payment_reference'),
        ('financiar', '0006_alter_bankstatementitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementitem',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankstatementitem',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documente.document'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='third_party_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru'),
        ),
    ]
