# Generated by Django 4.1.7 on 2024-09-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0028_alter_participareeveniment_detalii'),
        ('structuri', '0021_membru_data_initiala_cotizatie_and_more'),
        ('proiecte', '0008_alter_projectactivity_options_and_more'),
        ('financiar', '0009_paymentdomain_paymentdocument_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdocument',
            name='project_budget_item',
        ),
        migrations.RemoveField(
            model_name='paymentdocument',
            name='project_budget_line',
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eveniment'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valoare'),
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structuri.utilizator')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('role', models.IntegerField(choices=[(0, 'Cheltuială'), (1, 'Avans'), (2, 'Plată decont')], default=0)),
                ('details', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiar.paymentdocument')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiar.reimbursementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocumentBudgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiar.paymentdocument')),
                ('project_budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proiecte.projectbudgetentry')),
                ('project_budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proiecte.projectbudgetline')),
            ],
        ),
    ]
