# Generated by Django 4.1.7 on 2024-09-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0021_membru_data_initiala_cotizatie_and_more'),
        ('financiar', '0010_remove_paymentdocument_project_budget_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdocumentbudgetmapping',
            name='payment_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_mappings', to='financiar.paymentdocument'),
        ),
        migrations.AlterField(
            model_name='paymentdocumentfile',
            name='payment_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='financiar.paymentdocument'),
        ),
        migrations.AlterField(
            model_name='reimbursementpaymentdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='financiar.reimbursementrequest'),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='structuri.utilizator'),
        ),
    ]
