# Generated by Django 4.1.7 on 2023-06-02 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structuri', '0008_echipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('gpx_file', models.FileField(upload_to='locuri/gps/')),
                ('place_start', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('time_start', models.DateTimeField()),
                ('place_end', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('time_end', models.DateTimeField()),
                ('positive_altitude', models.IntegerField()),
                ('negative_altitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField()),
                ('name', models.CharField(max_length=1024)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('contact_person_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField()),
                ('name', models.CharField(max_length=1024)),
                ('space', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('contact_person_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
