# Generated by Django 4.1.7 on 2023-07-21 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locuri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='process_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Processed')], default=0),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
