# Generated by Django 4.1.7 on 2023-07-21 01:13

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locuri', '0002_gpxtrack_created_by_gpxtrack_process_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpx_file',
            field=models.FileField(upload_to='locuri/gps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx'])], verbose_name='Fișier GPX'),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='place_end',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='place_start',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL sursă'),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nume'),
        ),
    ]
