# Generated by Django 4.1.7 on 2023-07-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locuri', '0003_alter_gpxtrack_gpx_file_alter_gpxtrack_place_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrack',
            name='negative_altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='positive_altitude',
            field=models.IntegerField(default=0),
        ),
    ]
