# Generated by Django 4.1.7 on 2023-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locuri', '0004_alter_gpxtrack_negative_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='highest_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='lowest_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='moving_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='negative_altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='positive_altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
