# Generated by Django 4.1.7 on 2023-06-04 22:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('place', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ha_base_url', models.URLField(blank=True, null=True)),
                ('ha_access_token', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyControlElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ha_id', models.CharField(max_length=255)),
                ('service_action', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(null=True)),
                ('control_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertycontrolelement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('control_data', models.JSONField(default=dict)),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Failure')], default=1)),
                ('control_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertycontrolelement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
