# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantece', '0004_auto_20151130_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantec',
            name='nume_fisier',
            field=models.FilePathField(verbose_name='/home/yeti/PycharmProjects/scoutfile/media/cartecantece/cantece'),
        ),
        migrations.AlterField(
            model_name='conexiunecanteccarte',
            name='status',
            field=models.CharField(choices=[('propus', 'Propus'), ('aprobat', 'Aprobat'), ('respins', 'Respins')], max_length=255),
        ),
    ]
