# Generated by Django 4.1.7 on 2023-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantece', '0005_auto_20211031_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantec',
            name='nume_fisier',
            field=models.FilePathField(verbose_name='/home/yeti/projects/scoutfile/media/cartecantece/cantece'),
        ),
    ]
