# Generated by Django 4.1.7 on 2023-06-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_discussionitem_topic_alter_topic_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionitem',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='discussionitem',
            name='topic_path',
            field=models.CharField(db_index=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussionitem',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.discussionitem', verbose_name='replies'),
        ),
        migrations.AlterField(
            model_name='discussionitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='voting.topic'),
        ),
    ]
