# Generated by Django 4.1.7 on 2023-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_discussionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingoption',
            name='carries_motion',
            field=models.BooleanField(default=False),
        ),
    ]
