# Generated by Django 4.1.7 on 2023-06-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_votingoption_carries_motion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionitem',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Organic'), (2, 'Email'), (3, 'Slack')], default=1),
        ),
        migrations.AlterField(
            model_name='discussionitem',
            name='topic_path',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='discussionitem',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingoption'),
        ),
    ]
