# Generated by Django 4.1.7 on 2023-06-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_discussionitem_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionitem',
            old_name='topic_path',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='discussionitem',
            name='parent_topic',
        ),
        migrations.AddField(
            model_name='discussionitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='voting.discussionitem'),
        ),
    ]
