# Generated by Django 4.1.7 on 2024-09-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_rename_topic_path_discussionitem_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='voting.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, to='voting.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Subiect general'), (2, 'Decizie')], default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Organic'), (2, 'Slack'), (3, 'Email')], default=1),
        ),
    ]
