# Generated by Django 4.1.7 on 2024-09-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('voting', '0007_topic_parent_topic_related_topics_topic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='allowed_voting_roles',
            field=models.ManyToManyField(blank=True, to='structuri.tipasocierestructurastructura'),
        ),
        migrations.AddField(
            model_name='topic',
            name='structure_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='topic',
            name='structure_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
