# Generated by Django 4.1.7 on 2023-02-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_alter_photo_image_alter_watermark_image'),
        ('structuri', '0008_echipa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagineprofil',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='photologue.photoeffect', verbose_name='effect'),
        ),
    ]
