# Generated by Django 4.1.7 on 2023-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0008_echipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='slack_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
