# Generated by Django 4.1.7 on 2023-06-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0010_utilizator_slack_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgemeritmembru',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgemeritmembru',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='badgemeritmembru',
            name='membru',
        ),
        migrations.RemoveField(
            model_name='etapaprogres',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='etapaprogres',
            name='ramura_de_varsta',
        ),
        migrations.RemoveField(
            model_name='etapaprogresmembru',
            name='etapa_progres',
        ),
        migrations.RemoveField(
            model_name='etapaprogresmembru',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='etapaprogresmembru',
            name='membru',
        ),
        migrations.RemoveField(
            model_name='notatargetetapaprogres',
            name='activitate',
        ),
        migrations.RemoveField(
            model_name='notatargetetapaprogres',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='notatargetetapaprogres',
            name='membru',
        ),
        migrations.RemoveField(
            model_name='notatargetetapaprogres',
            name='target',
        ),
        migrations.RemoveField(
            model_name='noteobiectivprogresmembru',
            name='activitate',
        ),
        migrations.RemoveField(
            model_name='noteobiectivprogresmembru',
            name='etapa_progres',
        ),
        migrations.RemoveField(
            model_name='noteobiectivprogresmembru',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='noteobiectivprogresmembru',
            name='membru',
        ),
        migrations.RemoveField(
            model_name='noteobiectivprogresmembru',
            name='obiectiv',
        ),
        migrations.RemoveField(
            model_name='targetetapaprogres',
            name='content_type',
        ),
        migrations.AddField(
            model_name='centrulocal',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='echipa',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patrula',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitate',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BadgeMerit',
        ),
        migrations.DeleteModel(
            name='BadgeMeritMembru',
        ),
        migrations.DeleteModel(
            name='EtapaProgres',
        ),
        migrations.DeleteModel(
            name='EtapaProgresMembru',
        ),
        migrations.DeleteModel(
            name='NotaTargetEtapaProgres',
        ),
        migrations.DeleteModel(
            name='NoteObiectivProgresMembru',
        ),
        migrations.DeleteModel(
            name='ObiectivEducativProgres',
        ),
        migrations.DeleteModel(
            name='TargetEtapaProgres',
        ),
    ]
