# Generated by Django 4.1.7 on 2023-06-13 13:04

from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0011_remove_badgemeritmembru_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membru',
            name='cont_bancar',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False),
        ),
    ]
