# Generated by Django 4.1.7 on 2023-06-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_alter_photo_image_alter_watermark_image'),
        ('structuri', '0012_membru_cont_bancar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilizator',
            name='nume_nastere',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AlternateEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_on', models.DateTimeField()),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_emails', to='structuri.utilizator')),
            ],
        ),
    ]
