# Generated by Django 4.1.7 on 2023-06-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documente', '0007_platacotizatietrimestru_payment_reference'),
        ('structuri', '0013_utilizator_email_confirmed_utilizator_nume_nastere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asocieremembrustructura',
            name='documente',
            field=models.ManyToManyField(blank=True, to='documente.document'),
        )
    ]
