# Generated by Django 4.1.7 on 2023-07-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0014_asocieremembrustructura_documente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asocieremembrufamilie',
            name='same_budget',
            field=models.BooleanField(default=True, help_text='Cercetașii membri ai aceleiași familii care se întrețin din același buget sunt eligibili pentru sprijin financiar', verbose_name='Același buget'),
        ),
    ]
