# Generated by Django 4.1.7 on 2023-07-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0015_asocieremembrufamilie_same_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='porecla',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='nume_nastere',
            field=models.CharField(blank=True, help_text='Nume înainte de căsătorie / schimbare', max_length=255, verbose_name='Nume anterior'),
        ),
    ]
