# Generated by Django 4.1.7 on 2023-07-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0009_paymentdomain_paymentdocument_domain'),
        ('structuri', '0017_asocieremembrufamilie_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrulocal',
            name='default_payment_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centru_local', to='financiar.paymentdomain'),
        ),
    ]
