# Generated by Django 4.1.7 on 2023-09-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0018_centrulocal_default_payment_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrulocal',
            name='tip_centru_local',
            field=models.CharField(choices=[('centru_local', 'Centru Local'), ('centru_cercetasesc', 'Centru Cercetășesc')], default='centru_local', max_length=50),
        ),
        migrations.AlterField(
            model_name='patrula',
            name='unitate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_patrols', to='structuri.unitate'),
        ),
    ]
