# Generated by Django 4.1.7 on 2023-12-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0019_centrulocal_tip_centru_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membru',
            name='current_centru_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.centrulocal'),
        ),
    ]
