# Generated by Django 4.1.7 on 2024-09-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('structuri', '0021_membru_data_initiala_cotizatie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echipa',
            name='centru_local',
        ),
        migrations.AddField(
            model_name='centrulocal',
            name='group_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='echipa',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echipa',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echipa',
            name='group_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patrula',
            name='group_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unitate',
            name='group_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='TipAsociereStructuraStructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('content_types', models.ManyToManyField(blank=True, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('data_infiintare', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('slack_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('local_structures', models.ManyToManyField(to='structuri.centrulocal')),
            ],
            options={
                'verbose_name': 'Organizație',
                'verbose_name_plural': 'Organizații',
            },
        ),
        migrations.CreateModel(
            name='AsociereStructuraStructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_structure_id', models.PositiveIntegerField()),
                ('target_structure_id', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structuri.tipasocierestructurastructura')),
                ('source_structure_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_structures', to='contenttypes.contenttype')),
                ('target_structure_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_structures', to='contenttypes.contenttype')),
            ],
        ),
    ]
