# Generated by Django 5.1.1 on 2024-11-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0022_remove_echipa_centru_local_centrulocal_group_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagineprofil',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='photologue.photoeffect', verbose_name='effect'),
        ),
    ]
