# Generated by Django 4.1.7 on 2023-06-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documente', '0007_platacotizatietrimestru_payment_reference'),
        ('album', '0015_eventcertification_alter_eveniment_status_and_more'),
        ('structuri', '0011_remove_badgemeritmembru_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='certificari/icons/')),
                ('source', models.CharField(choices=[('internal', 'Internă'), ('external', 'Externă')], default='internal', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('issued_by', models.CharField(blank=True, max_length=1024)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificari.certificationtype')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documente.document')),
                ('event_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='album.eveniment')),
                ('events', models.ManyToManyField(blank=True, related_name='contributed_certificates', to='album.eveniment')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificari', to='structuri.membru')),
            ],
        ),
    ]
