# Generated by Django 4.1.7 on 2023-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='validity',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
