# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0007_auto_20211031_2218'),
        ('inventar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocateiInventar',
            new_name='LocatieInventar',
        ),
        migrations.AlterField(
            model_name='iesireinventar',
            name='motiv',
            field=models.CharField(choices=[('activitate', 'Activitate'), ('imprumut', 'Împrumut'), ('casare', 'Casare'), ('distrugere', 'Distrugere')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrareinventar',
            name='iesire_inventar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventar.IesireInventar'),
        ),
        migrations.AlterField(
            model_name='obiectinventar',
            name='stare',
            field=models.CharField(choices=[('nou', 'Nou'), ('fb', 'Foarte bună'), ('b', 'Bună'), ('u', 'Utilizabil'), ('r', 'Are nevoie de reparații'), ('p', 'Proastă')], max_length=255),
        ),
    ]
