# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='poza_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Imagine'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='status',
            field=models.CharField(default='produs', max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='tip',
            field=models.CharField(choices=[('eveniment', 'Eveniment'), ('progres', 'Progres'), ('merit', 'Merit'), ('altul', 'Alt tip de badge')], max_length=255),
        ),
    ]
