# Generated by Django 4.1.7 on 2023-06-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0012_alter_imagine_effect'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('structuri', '0011_remove_badgemeritmembru_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeMerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('ordine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('reguli', models.CharField(blank=True, max_length=1024, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.imagine')),
                ('ramura_de_varsta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structuri.ramuradevarsta')),
            ],
        ),
        migrations.CreateModel(
            name='ObiectivEducativProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=2048)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('domeniu', models.CharField(choices=[('intelectual', 'Intelectual'), ('fizic', 'Fizic'), ('afectiv', 'Afectiv'), ('social', 'Social'), ('caracter', 'Caracter'), ('spiritual', 'Spiritual')], max_length=255)),
                ('pista', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetEtapaProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=2048)),
                ('capitol', models.CharField(max_length=2048)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='NoteObiectivProgresMembru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('obiectiv_atins', models.BooleanField(default=False)),
                ('activitate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eveniment')),
                ('etapa_progres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.etapaprogres')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_obiective_progres_evaluate', to='structuri.membru')),
                ('membru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_obiective_progres', to='structuri.membru')),
                ('obiectiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.obiectiveducativprogres')),
            ],
        ),
        migrations.CreateModel(
            name='NotaTargetEtapaProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_atins', models.BooleanField(default=False)),
                ('activitate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eveniment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_etape_progres_evaluate', to='structuri.membru')),
                ('membru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_etape_progres', to='structuri.membru')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.targetetapaprogres')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProgresMembru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('detalii', models.TextField(blank=True, null=True)),
                ('etapa_progres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.etapaprogres')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape_progres_evaluate', to='structuri.membru')),
                ('membru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape_progres', to='structuri.membru')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeMeritMembru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('detalii', models.TextField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.badgemerit')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeuri_merit_evaluate', to='structuri.membru')),
                ('membru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeuri_merit', to='structuri.membru')),
            ],
        ),
        migrations.AddField(
            model_name='badgemerit',
            name='etapa_progres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.etapaprogres'),
        ),
        migrations.AddField(
            model_name='badgemerit',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.imagine'),
        ),
        migrations.AddField(
            model_name='badgemerit',
            name='ramura_de_varsta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structuri.ramuradevarsta'),
        ),
    ]
