# Generated by Django 4.1.7 on 2023-06-14 11:41

from django.db import migrations, models
import redirects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ref', models.CharField(default='', max_length=255, null=True, verbose_name='Reference')),
                ('token', models.CharField(db_index=True, default=redirects.models.generate_token, max_length=30, unique=True)),
                ('to_url', models.CharField(max_length=255)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('tag_type', models.PositiveIntegerField(choices=[(1, 'QR Code'), (2, 'RFID')], default=1)),
            ],
        ),
    ]
