# Generated by Django 2.0 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrocle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Clasă'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='tip',
            field=models.CharField(choices=[(1, 'Real'), (2, 'Intern')], max_length=2),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrocle.Credit'),
        ),
    ]
