# Generated by Django 4.1.7 on 2023-06-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0010_utilizator_slack_email'),
        ('album', '0008_auto_20211031_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEveniment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('color', models.CharField(default='FFFFFF', max_length=6)),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.eveniment')),
                ('responsabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEveniment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('color', models.CharField(default='FFFFFF', max_length=6)),
                ('moment_inceput', models.DateTimeField()),
                ('moment_sfarsit', models.DateTimeField()),
                ('materiale', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.programeveniment')),
                ('responsabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru')),
                ('tracks', models.ManyToManyField(to='album.trackeveniment')),
            ],
        ),
    ]
