# Generated by Django 4.1.7 on 2023-06-04 22:30

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_eveniment_frecventa_eveniment_instanta_anterioara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociereevenimentstructura',
            name='slack_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eveniment',
            name='locatie',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveniment',
            name='slack_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eveniment',
            name='text_invitatie',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participareeveniment',
            name='status_participare',
            field=models.IntegerField(choices=[(1, 'Cu semnul întrebării'), (2, 'Confirmat'), (8, 'Refuzat invitația'), (3, 'Avans plătit'), (4, 'Participare efectivă'), (7, 'Participare efectivă (fizic)'), (6, 'Participare efectivă (online)'), (5, 'Participare anulată'), (9, 'Necunoscut'), (10, 'Plata confirmată')], default=9),
        ),
    ]
