# Generated by Django 4.1.7 on 2023-06-08 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_asociereevenimentstructura_slack_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveniment',
            name='locatie',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='eveniment',
            name='text_invitatie',
            field=models.TextField(blank=True),
        ),
    ]
