# Generated by Django 4.1.7 on 2023-06-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiar', '0007_bankstatementitem_notes_bankstatementitem_registered_and_more'),
        ('album', '0013_alter_eveniment_locatie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participareeveniment',
            name='contribution_option',
            field=models.ForeignKey(blank=True, help_text='Tip contribuție', null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eventcontributionoption'),
        ),
        migrations.AlterField(
            model_name='participareeveniment',
            name='contribution_payments',
            field=models.ManyToManyField(blank=True, help_text='Plăți contribuție', related_name='payments', to='financiar.paymentdocument'),
        ),
    ]
