# Generated by Django 4.1.7 on 2023-06-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_eventcertification_alter_eveniment_status_and_more'),
        ('certificari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificari.certificationtype'),
        ),
        migrations.AddField(
            model_name='eventcertification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificari', to='album.eveniment'),
        ),
    ]
