# Generated by Django 4.1.7 on 2023-07-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_eventcertification_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
