# Generated by Django 4.1.7 on 2023-07-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0017_alter_eventcontributionoption_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment',
            name='external_album_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link album extern'),
        ),
    ]
