# Generated by Django 4.1.7 on 2023-07-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0018_eveniment_external_album_link_alter_imagine_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='description',
            field=models.TextField(blank=True, help_text='Explicație pentru situațiile în care se aplică această contribuție', verbose_name='Descriere'),
        ),
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Implicit'),
        ),
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='per_diem',
            field=models.BooleanField(default=False, verbose_name='Pe zi'),
        ),
        migrations.AlterField(
            model_name='eventcontributionoption',
            name='value',
            field=models.FloatField(verbose_name='Valoare'),
        ),
        migrations.AlterField(
            model_name='participareeveniment',
            name='contribution_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.eventcontributionoption', verbose_name='Tip contribuție'),
        ),
    ]
