# Generated by Django 4.1.7 on 2023-07-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documente', '0008_chitanta_payment_document'),
        ('album', '0019_alter_eventcontributionoption_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eveniment',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='evenimente', to='documente.document'),
        ),
        migrations.CreateModel(
            name='EventURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='album.eveniment')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.linktype')),
            ],
        ),
    ]
