# Generated by Django 4.1.7 on 2023-07-15 11:54

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    LinkType = apps.get_model("album", "LinkType")
    db_alias = schema_editor.connection.alias
    lt = LinkType.objects.using(db_alias).create(
        name="Album extern"
    )

    Eveniment = apps.get_model("album", "Eveniment")
    EventURL = apps.get_model("album", "EventURL")
    for e in Eveniment.objects.using(db_alias).filter(external_album_link__isnull=False).exclude(external_album_link=""):
        EventURL.objects.using(db_alias).create(url=e.external_album_link, role=lt, eveniment=e)

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    LinkType = apps.get_model("album", "LinkType")
    db_alias = schema_editor.connection.alias
    LinkType.objects.using(db_alias).filter(name="Album extern").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('album', '0020_linktype_eveniment_documents_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
