# Generated by Django 4.1.7 on 2023-07-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuri', '0018_centrulocal_default_payment_domain_and_more'),
        ('locuri', '0005_gpxtrack_duration_gpxtrack_highest_point_and_more'),
        ('album', '0023_unique_participare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagine',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='photologue.photoeffect', verbose_name='effect'),
        ),
        migrations.CreateModel(
            name='EventGPXTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpx_tracks', to='album.eveniment')),
                ('membri', models.ManyToManyField(blank=True, to='structuri.membru')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed', to='album.eventgpxtrack')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locuri.gpxtrack')),
            ],
        ),
    ]
