# Generated by Django 4.1.7 on 2023-09-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0024_eventgpxtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='participareeveniment',
            name='participant_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asociereevenimentstructura',
            name='eveniment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asocieri_structura', to='album.eveniment'),
        ),
        migrations.AlterField(
            model_name='participareeveniment',
            name='status_participare',
            field=models.IntegerField(choices=[(1, 'Cu semnul întrebării'), (2, 'Confirmat'), (8, 'Refuzat invitația'), (3, 'Avans plătit'), (4, 'Participare efectivă'), (7, 'Participare efectivă (fizic)'), (6, 'Participare efectivă (online)'), (5, 'Participare anulată'), (9, 'Necunoscut'), (10, 'Plata confirmată'), (11, 'Invitat'), (12, 'Eveniment anulat'), (13, 'Respins de organizator')], default=9),
        ),
    ]
