# Generated by Django 4.1.7 on 2023-09-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0025_participareeveniment_participant_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camparbitrarparticipareeveniment',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='camparbitrarparticipareeveniment',
            name='eveniment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuri_arbitrare', to='album.eveniment'),
        ),
    ]
