# Generated by Django 4.1.7 on 2024-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0026_camparbitrarparticipareeveniment_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camparbitrarparticipareeveniment',
            name='config',
            field=models.JSONField(default=dict, help_text='Configurare adițională, opțională'),
        ),
        migrations.AlterField(
            model_name='camparbitrarparticipareeveniment',
            name='tip_camp',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Număr'), ('bool', 'Bifă'), ('date', 'Dată'), ('choice', 'Listă')], max_length=255),
        ),
        migrations.AlterField(
            model_name='participareeveniment',
            name='detalii',
            field=models.TextField(default=''),
        ),
    ]
