# Generated by Django 4.1.7 on 2024-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0027_alter_camparbitrarparticipareeveniment_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participareeveniment',
            name='detalii',
            field=models.TextField(blank=True, default=''),
        ),
    ]
