# Generated by Django 4.1.7 on 2023-06-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structuri', '0012_membru_cont_bancar_alter_imagineprofil_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact_person_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=14)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (3, 'Assigned to unit'), (4, 'Accepted (by person)'), (5, 'Rejected (by person)'), (6, 'Delayed')], default=0)),
                ('family', models.ManyToManyField(blank=True, related_name='waitinglist_family', to='structuri.membru')),
                ('membru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structuri.membru')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitinglist_recommendations', to='structuri.membru')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (3, 'Assigned to unit'), (4, 'Accepted (by person)'), (5, 'Rejected (by person)'), (6, 'Delayed')])),
                ('new_status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (3, 'Assigned to unit'), (4, 'Accepted (by person)'), (5, 'Rejected (by person)'), (6, 'Delayed')])),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Phoned'), (2, 'Emailed'), (3, 'Assigned'), (4, 'Closed (either rejected or accepted)')])),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structuri.membru')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiting_list.waitinglistperson')),
            ],
        ),
    ]
