# Generated by Django 4.1.7 on 2023-06-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistperson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structuri.centrulocal'),
            preserve_default=False,
        ),
    ]
