name: deploy-to-staging
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PORT: ${{ vars.SSH_PORT }}

      - name: Stop the server
        run: ssh staging 'sudo supervisorctl stop scoutfile-develop'

      - name: Check out the source
        run: ssh staging 'cd releases/develop && git fetch && git reset --hard origin/develop'

      - name: Make sure to update python packages
        run: ssh staging 'cd releases/develop && pip install -r deploy/requirements.txt'

      - name: Run migrations
        run: ssh staging 'cd releases/develop/web && ../.venv/bin/python manage.py migrate'

      - name: Gather static files
        run: ssh staging 'cd releases/develop/web && ../.venv/bin/python manage.py collectstatic --noinput'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo supervisorctl start scoutfile-develop'
